spring:
  redis:
    database: 15
    host: 127.0.0.1
    jedis:
      pool:
        max-active: 100
        max-idle: 8
        max-wait: 60000
        min-idle: 0
    password:
    port: 6379
    timeout: 1000
logging:
  level:
    com.fastDev4j: debug
    org.springframework: warn

mybatis-plus:
  mapperLocations: classpath*:mapper/**/**.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
